{
 "title": "Scale Testing",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Normal Events by Reason",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (reason) (rate(kube_event_count{type=\"Normal\"}[$__rate_interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Warning Events by Reason",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (reason) (rate(kube_event_count{type=\"Warning\"}[$__rate_interval]))",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  { "title": "Crossplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Reconciles by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by (controller) (rate(controller_runtime_reconcile_total{job=~\"upbound-system/.*\"}[$__rate_interval])))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "API Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(rest_client_requests_total{job=~\"upbound-system/.*\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (workqueue_depth{job=~\"upbound-system/.+\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Duration",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"upbound-system/.+\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU Limit Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"upbound-system\", container!=\"\"}[5m])) by (pod, container)\n/\nsum(container_spec_cpu_quota{namespace=\"upbound-system\", container!=\"\"} / container_spec_cpu_period{namespace=\"upbound-system\", container!=\"\"}) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Limit Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"upbound-system\"}) by (container, pod)\n/\nsum(kube_pod_container_resource_limits{namespace=\"upbound-system\"} > 0) by (container, pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "API Server Requests by Resource (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (resource) (rate(apiserver_request_total[$__rate_interval])))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Server Errors by Resource and Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code, resource) (rate(apiserver_request_total{code=~\"[45][0-9][0-9]\"}[$__rate_interval]))",
     "legendFormat": "{{code}} ({{resource}})"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API Server Started",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"apiserver\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{job=\"apiserver\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server CRDs Added",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "count(count by (crd) (apiextensions_openapi_v2_regeneration_count{job=\"apiserver\", reason=\"add\"}))",
     "legendFormat": "CRDs"
    }
   ]
  },
  {
   "title": "API Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (process_resident_memory_bytes{job=\"apiserver\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 39 },
   "targets": [
    {
     "expr": "sum by (instance) (go_goroutines{job=\"apiserver\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}